---
# tasks file for ansible-hwraid

# Copyright (C) 2014-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Select supported release for current distribution
  set_fact:
    hwraid_register_release: |
      {{ hwraid_release if (hwraid_release in hwraid_distribution_releases[hwraid_distribution])
                        else hwraid_distribution_releases[hwraid_distribution][0] }}

- name: Get list of active kernel modules
  shell: |
    set -o nounset -o pipefail -o errexit
    lsmod | cut -d' ' -f 1 -s | sort -u
  args:
    executable: /bin/bash
  register: hwraid_register_modules
  changed_when: false
  check_mode: false

- name: install packages
  import_tasks: apt.yml
  when:
    - hwraid_register_release is defined
    - hwraid_register_release | length > 0

- name: additional scripts
  import_tasks: scripts.yml
  when:
    - hwraid_register_release is defined
    - hwraid_register_release | length > 0
