---
- name: hwraid | scripts | copy scripts to host scripts directory
  template:
    src: "usr/local/scripts/{{ item.module }}-disk-status.sh.j2"
    dest: "/usr/local/scripts/{{ item.module }}-disk-status.sh"
    backup: no
    owner: root
    group: adm
    mode: 0755

- name: hwraid | create cron job for count all disk to pushgateway
  cron:
    name: "{{ item.module }} count all disk"
    cron_file: hwraid_tasks
    user: root
    minute: '*/2'
    job: "/usr/local/scripts/{{ item.module }}-disk-status.sh count-all"
    state: "{{ hwraid_cron_enabled | ternary('present', 'absent') }}"

- name: hwraid | create cron job for count failed disk to pushgateway
  cron:
    name: "{{ item.module }} count failed disk"
    cron_file: hwraid_tasks
    user: root
    minute: '*/2'
    job: "/usr/local/scripts/{{ item.module }}-disk-status.sh count-failed"
    state: "{{ hwraid_cron_enabled | ternary('present', 'absent') }}"
